name: Test on GH actions environment

on: 
  - push
  - pull_request

env:
  py: "3.13"
  
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
          - os: macOS-latest
          - os: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.py }}

      - name: Install deps
        run: choco install 7zip
        if: matrix.os == 'windows-latest'  

      - name: Install deps
        run: brew install yasm nasm pkg-config 7zip
        if: matrix.os == 'macOS-latest'

      # We also run out of space on ubuntu if we don't do an apt-get clean after installing
      - name: Update apt and install deps
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y yasm nasm gperf libgles2-mesa-dev libx11-dev libxft-dev libxext-dev libxrandr-dev libxi-dev libxcursor-dev libxdamage-dev libxinerama-dev libdbus-1-dev libxtst-dev build-essential g++ apt-transport-https ca-certificates gnupg software-properties-common zlib1g p7zip-full
          sudo apt clean

      - name: print disk space
        shell: bash
        run: df -h || echo "df -h failed"

      - name: Build Standalone binary
        shell: pwsh
        env:
          IS_CI: true
        run: ${{ github.workspace }}/scripts/build-standalone.ps1

        # We need to clean before zipping or we might run out of space on the runners
      - name: Clean
        run: |
          mv dist dist_tmp
          ${{ github.workspace }}/scripts/build-clean.ps1
          mv dist_tmp dist
        shell: pwsh

      - name: Zip artifact
        run: |
          cd ${{ github.workspace }}/dist
          7z a -r ocr_aggregator_server_${{ matrix.os }}.zip ocr_aggregator_server
        shell: pwsh

      - uses: actions/upload-artifact@v6
        continue-on-error: true
        with:
          name: ocr_aggregator_server_${{ matrix.os }}
          path: ${{ github.workspace }}/dist/ocr_aggregator_server_${{ matrix.os }}.zip
